"use client";
import Link from "next/link"; import { motion } from "framer-motion"; import { ArrowRight, Brain, ChevronRight, Clock3, Crown, Medal, Search, Trophy, Users } from "lucide-react";
import type { Challenge } from "@/lib/api";
export const Button=({children,href,className="",...props}:{children:React.ReactNode;href?:string;className?:string}&React.ButtonHTMLAttributes<HTMLButtonElement>)=> href?<Link href={href} className={`inline-flex items-center justify-center gap-2 rounded-sm bg-[#1F2937] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#679436] ${className}`}>{children}</Link>:<button {...props} className={`inline-flex items-center justify-center gap-2 rounded-sm bg-[#1F2937] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#679436] disabled:opacity-50 ${className}`}>{children}</button>;
export function Wordmark(){return <Link href="/" className="group flex items-center gap-2" aria-label="Mada Champion, accueil"><span className="grid h-9 w-9 place-items-center bg-[#679436] text-white"><Trophy size={19}/></span><span className="display text-xl leading-none">MADA<br/><i className="not-italic text-[#679436]">CHAMPION</i></span></Link>}
export function Nav(){return <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6"><Wordmark/><nav className="hidden items-center gap-7 text-sm font-bold md:flex"><a href="#competitions">Compétitions</a><a href="#principe">Le principe</a><a href="#palmares">Palmarès</a></nav><div className="flex gap-2"><Link className="px-4 py-2 text-sm font-bold" href="/login">Connexion</Link><Button href="/register" className="px-4 py-2">Participer</Button></div></header>}
export function Status({status}:{status:string}){const map:Record<string,string>={RUNNING:"bg-red-100 text-red-800",WAITING:"bg-[#e5f4ed] text-[#08734b]",SCHEDULED:"bg-[#eff3e9] text-[#547f29]",FINISHED:"bg-slate-100 text-slate-600",DRAFT:"bg-amber-100 text-amber-800"}; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black tracking-widest ${map[status]||map.DRAFT}`}>{status}</span>}
export function ChallengeCard({challenge,action=true}:{challenge:Challenge;action?:boolean}){return <article className="group border border-[#D7DFD0] bg-white p-5 transition hover:-translate-y-1 hover:border-[#679436] hover:shadow-xl hover:shadow-[#679436]/10"><div className="mb-7 flex items-start justify-between"><span className="text-xs font-black uppercase tracking-widest text-[#679436]">{challenge.category}</span><Status status={challenge.status}/></div><h3 className="display text-2xl leading-none">{challenge.title}</h3><p className="mt-3 min-h-10 text-sm leading-5 text-slate-500">{challenge.description || "Un défi de culture générale pour tester votre précision."}</p><div className="mt-6 flex justify-between border-t border-[#D7DFD0] pt-4 text-xs font-bold text-slate-600"><span className="flex items-center gap-1"><Clock3 size={14}/>{new Intl.DateTimeFormat("fr-MG",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(challenge.scheduled_at))}</span><span className="flex items-center gap-1"><Users size={14}/> {challenge.max_participants}</span></div>{action&&<Link href={`/challenges/${challenge.id}/lobby`} className="mt-5 flex items-center justify-between text-sm font-black text-[#1F2937]">Voir le défi <ArrowRight size={16} className="transition group-hover:translate-x-1"/></Link>}</article>}
export function SectionTitle({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}) {return <div className="max-w-2xl"><p className="mb-3 text-xs font-black uppercase tracking-[.22em] text-[#679436]">{eyebrow}</p><h2 className="display text-4xl leading-[.9] md:text-6xl">{title}</h2>{copy&&<p className="mt-5 leading-7 text-slate-600">{copy}</p>}</div>}
export function MiniRank(){return <div className="border-l border-[#D7DFD0] pl-5"><p className="mb-4 text-xs font-black uppercase tracking-widest text-slate-500">Classement en direct</p>{[["01","Lova","2 480"],["02","Vous","2 410"],["03","Tiana","2 260"]].map(([rank,name,points],i)=><motion.div initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} transition={{delay:i*.1}} key={name} className={`mb-3 flex items-center justify-between text-sm ${name==="Vous"?"font-black text-[#0FAC71]":""}`}><span><b className="mr-3 text-[#8C9C7C]">{rank}</b>{name}</span><b>{points}</b></motion.div>)}</div>}
export const icons={Brain,ChevronRight,Crown,Medal,Search,Trophy,Users};
